### ISSUE TITLE
Still receiving "Username is already logged in" error 

### ISSUE THREAD

**Issue by twothousandandone** [Open-RSC/Single-Player#14]
After backing up my database from v2.3.2c  and restoring it with v2.3.3 - Still receiving the "That username is already logged in message" after logging out. 

This error also occurs with a fresh/reset database

![2019-02-15_07-32-31](https://user-images.githubusercontent.com/47410572/52857017-e6455380-30f3-11e9-81a4-5c60159418fb.png)

![java_2019-02-15_07-11-21](https://user-images.githubusercontent.com/47410572/52856104-8188f980-30f1-11e9-9222-d43a49d26bf2.png)

**Comment by Marwolf** [comment]
Fixed in #21
