### ISSUE TITLE
Optional config to remove/null email address field in account creation

### ISSUE THREAD

**Issue by twothousandandone** [Open-RSC/Single-Player#15]
Config option to remove or nullify the email address field in the "New User"/account creation screen could be considered.

This would not be something marked as "100 percent authentic" and instead would be "QOL"

![java_2019-02-15_07-18-24](https://user-images.githubusercontent.com/47410572/52856259-ed6b6200-30f1-11e9-806d-3ed8a82f9a95.png)

**Comment by Marwolf** [comment]
Email entry and requirement disabled/hidden by default
