### ISSUE TITLE
Account creation time-limit could be removed 

### ISSUE THREAD

**Issue by twothousandandone** [Open-RSC/Single-Player#16]
![java_2019-02-15_07-44-16](https://user-images.githubusercontent.com/47410572/52858342-d4fe4600-30f7-11e9-95de-375424bb836a.png)

Account creation timer from live server appears to be active in single player 

"_You have registered recently_
_to prevent flooding, wait an hour._"

If this could be removed it may be beneficial, as restarting the client is currently the only way to bypass this timer.

**Comment by Marwolf** [comment]
Starting the game or opening a new game window will reset the creation date in the database for all players but this overall should be configured as it is not authentic to have a timer in the first place.

**Comment by Marwolf** [comment]
Now removed by default
